name: test suite
on: [push, pull_request]
env:
  NU_VERSION: 0.93.0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Nushell $NU_VERSION
        run: |
          curl -L https://github.com/nushell/nushell/releases/download/${NU_VERSION}/nu-${NU_VERSION}-x86_64-linux-gnu-full.tar.gz | tar xzf -
      - name: Run
        run: |
          echo $HOME
          ls -l $HOME
          ls -l $HOME/.config
          pwd
          ls -l
          ./nu-${NU_VERSION}-x86_64-linux-gnu-full/nu run-tests.nu
